name: Update README

on:
    push:
        branches: [main]
        paths:
            - "id_*/**"

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Build update script
              run: |
                  cd .github/scripts
                  cargo build --release

            - name: Update README
              run: |
                  ./.github/scripts/target/release/update_readme

            - name: Commit changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add README.md
                  git diff --quiet && git diff --staged --quiet || git commit -m "docs: update README with new solutions"
                  git push
